### ISSUE TITLE
Allow forking Paper-MojangAPI

### ISSUE THREAD

**Issue by notOM3GA** [PaperMC/paperweight#11]
This is a requirement for forks otherwise they end up with an error:
`Project with path ':Paper-MojangAPI' could not be found in project ':Purpur-Server'`

**Comment by jpenilla** [comment]
You can either

1) Point the project directory for Paper-MojangAPI to inside the Paper project

```kotlin
include("Paper-MojangAPI")
project(":Paper-MojangAPI").projectDir = file("Paper/Paper-MojangAPI")
```

2) Just depend on the published Paper-MojangAPI artifact on the Paper maven repository

Either of these solutions are fine unless you actually want to patch Paper-MojangAPI.

**Comment by notOM3GA** [comment]
i've worked out a solution by adding a custom upstream:
```kotlin
val initMojangApi by tasks.registering {
    val paperMojangApi = project.layout.cache.resolve("paperweight/upstreams/paper/Paper-MojangAPI").toFile()
    doLast {
        paperMojangApi.resolve(".git").deleteRecursively()
        Git(paperMojangApi)("init").executeOut()
        Git(paperMojangApi)("add", ".").executeOut()
        Git(paperMojangApi)("commit", "-m", "Initial Source", "--author=Initial <auto@mated.null>").executeOut()
    }
}

paperweight {
    upstreams {
        register("Paper") {
            upstreamDataTask.get().finalizedBy(initMojangApi)

            patchTasks.register("mojangApi") {
                sourceDir.set(project.layout.cache.resolve("paperweight/upstreams/paper/Paper-MojangAPI").toFile())
                patchDir.set(file("patches/mojangapi"))
                outputDir.set(file("Purpur-MojangAPI"))
            }
        }
    }
}
```

**Comment by Proximyst** [comment]
We should still have functionality to fork it properly as it's a component of the API (why it's not just part of paper-api is beyond me, though).

**Comment by MiniDigger** [comment]
its not in paper-api because we wanted to keep mojang code out (glowstone consumes paper-api).

am pretty sure denwav, leaf and I agreed that forking mojang api is not necessary, ever. does purpur actually patch it?

and I mean, paperweight is flexible enough that you cando it, like demonstrated above. considering purpur doesn't use the default stuff from paperweight patcher anyways, I don't think there is anything for us to do here?

**Comment by notOM3GA** [comment]
> does purpur actually patch it?
no we don't, I can do what jmp said and depend on it from the paper repo

**Comment by DenWav** [comment]
@notOM3GA minor nit-pick, not that it really matters, it would be better to lazily-configure the `upstreamDataTask` rather than calling `get()`:

```
paperweight {
    upstreams {
        register("Paper") {
            upstreamDataTask {
                finalizedBy(initMojangApi)
            }

            patchTasks.register("mojangApi") {
                sourceDir.set(project.layout.cache.resolve("paperweight/upstreams/paper/Paper-MojangAPI").toFile())
                patchDir.set(file("patches/mojangapi"))
                outputDir.set(file("Purpur-MojangAPI"))
            }
        }
    }
}
```

But otherwise that should work. I will see about doing that setup automatically in `paperweight` if MojangAPI is requested somehow.

> am pretty sure denwav, leaf and I agreed that forking mojang api is not necessary, ever.

I don't know of a reason why forking it would be necessary, but I won't speak for other forks and state that myself. If a fork wanted to do something there, seems reasonable enough to me. And `paperweight` is flexible enough as discussed earlier that adding this functionality is not a major issue.

**Comment by DenWav** [comment]
Example of a project which patches `Paper-MojangAPI`: https://github.com/PaperMC/paperweight-examples/tree/mojangapi
