### ISSUE TITLE
Support 1.17.1 in latest userdev

### ISSUE THREAD

**Issue by octylFractal** [PaperMC/paperweight#116]
It would be nice to have support for MC versions continuously through newer bundle versions, either through supporting the legacy bundle versions, or updating old MC versions to newer bundle versions.

**Comment by WillFP** [comment]
Additional information and why this is a problem:
I have a multi-module nms setup on my main library plugin [eco](https://github.com/Auxilor/eco/tree/develop) and I can't add support for both 1.17 and 1.18 because of this.
Because 1.17 and 1.18 require different userdev versions, this error happens: https://github.com/Auxilor/eco/runs/4345214019?check_suite_focus=true, where gradle is reading the dependency from the wrong version of paperweight and thus failing to sync the project.
This means that it's essentially impossible to add support for both 1.17 and 1.18 nms until this problem is fixed
