### ISSUE TITLE
Expose a task that can deobf plugin jars.

### ISSUE THREAD

**Issue by ryantheleach** [PaperMC/paperweight#132]
Debugging using MojangMappings (as a plugin) with plugin dependencies can be painful at the moment.

Hard depending on ProtocolLib for example, means that if you want to debug in a MojangMapping environment, you need to create or find a MojMapped ProtocolLib.

It would be useful to expose a task that was capable of applying the mappings in reverse, so that dependencies can be used while debugging.

**Comment by jpenilla** [comment]
You can run tiny-remapper using paper's reobf mappings. Make sure to include the reobf server on the remap classpath. This isn't something that will be made easier by paperweight, you should instead encourage other plugin developers to publish non-mangled jars.

**Comment by ryantheleach** [comment]
I fear that playing hard-ball with this chicken and egg adoption problem will result in lower adoption not more, but respect your decision.

**Comment by electronicboy** [comment]
I don't really see how this would fit inside of a grade plugin which the user dev potion of stuff is for producing a mapped jar and not much more, am not even sure how that would be exposed

An external tool for this would be interesting but then you start getting into having to try remapping reflective calls too, etc in order to actually be useful
