### ISSUE TITLE
Missed Mapping

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/paperweight#24]
![https://i.imgur.com/pN4IBO8.png](https://i.imgur.com/pN4IBO8.png)

I can see the mapping in spigot-mojang+yarn+fields.csrg:
net/minecraft/server/level/WorldServer E serverLevelData
and offical-spigot.tiny:
f	Ldih;	E	serverLevelData
but not in the reobf mappings or any of the other spigot-mojang mappings

mojang name for the class is ServerLevel

**Comment by MiniDigger** [comment]
List:

<table>
<tr>
	<th>Spigot class name
	<th>paper class name
	<th>spigot member 
	<th>paper member
<tr>
	<td>net/minecraft/commands/arguments/ArgumentMobEffect
	<td>MobEffectArgument
	<td>a	net.minecraft.world.effect.MobEffectList	[com.mojang.brigadier.context.CommandContext, java.lang.String]
	<td>getEffect	net.minecraft.world.effect.MobEffectList	[com.mojang.brigadier.context.CommandContext, java.lang.String]
<tr>
	<td>
	<td>
	<td>
	<td>
</table>

**Comment by MiniDigger** [comment]
another case to map manually https://github.com/PaperMC/Paper/issues/5884

**Comment by JorelAli** [comment]
Method `getResourceManager` in `net.minecraft.server.ServerResources` is not mapped to the Spigot `i` method

**Comment by DenWav** [comment]
Related commit: https://github.com/PaperMC/paperweight/commit/685abfa47e04744c1d6e9b2280bca59740c80b5e

**Comment by dawon** [comment]
Having this issue in the latest paper, is it related to this mappings problem (happens on the latest paper, but not in the latest spigot, while using the same versions of all plugins)?

https://pastebin.com/R617JSWS

**Comment by wizjany** [comment]
`java.lang.NoSuchMethodError: 'net.minecraft.world.level.storage.SaveData net.minecraft.server.dedicated.DedicatedServer.getSaveData()'`
method is getWorldData in paper, in MinecraftServer

**Comment by narcarsiss** [comment]
Another case here:  
[RE: fawe Crashing on certain commands - Tested on git-Paper-64, can't reproduce. This appears to be a mapping issue at Purpurs end. · Issue #1155 · IntellectualSites/FastAsyncWorldEdit (github.com)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1155)

**Comment by SirYwell** [comment]
That's completely unrelated, not a paperweight issue. Please **read** before randomly reporting things that have nothing to do with each other.

**Comment by BillyGalbreath** [comment]
> That's completely unrelated, not a paperweight issue. Please **read** before randomly reporting things that have nothing to do with each other.

It very much is a mapping issue caused by paperweight. I _told_ narcarsiss to report it here, as instructed by Denwav and Minidigger, since it keeps getting brushed off as Purpur issue by the plugin devs. Seeing the same error in _all_ forks that are using paperweight

Here's from Tuinity's discord, too:

![image](https://user-images.githubusercontent.com/332527/123920983-2798cf80-d94c-11eb-9baa-19ac699b92f6.png)

**Comment by DenWav** [comment]
I know a lot of people are waiting patiently for these issues to be fixed, but I haven't really looked at any of them yet due to lack of personal time recently and the long list of other features and things I have to fix and implement in paperweight.

I can only work on one thing at a time, and in general issues surrounding _using_ paperweight (in particular around forks since that's a much newer feature) takes priority over stuff like this. Note 2 things:

 1. I _will_ get to this, and hopefully soon, but it's all dependent on the stuff I've already mentioned.
 2. For particular plugin breakages that we are aware of, there is a mechanism to [band-aid the issue](https://github.com/PaperMC/Paper/blob/master/build-data/reobf-mappings-patch.tiny) temporarily.

For the second point, I haven't implemented the ability for forks to supply their own reobf mappings patches yet, but as with everything else it will come as soon as I'm able to get to it. For now, please PR new reobf mappings patches to Paper at least so when that's properly implemented all forks will get it.

**Comment by fierceeo** [comment]
Another case: The WorldServer in net.minecraft.world.level.chunk.Chunk should be mapped to net.minecraft.world.level.chunk.Chunk.i instead of net.minecraft.world.level.chunk.Chunk.level

**Comment by fierceeo** [comment]
Some more mappings that have been missed after the 1.17.1 update: https://github.com/PaperMC/paperweight/issues/52

**Comment by Foorcee** [comment]
`java.lang.NoSuchMethodError: 'net.minecraft.server.dedicated.DedicatedPlayerList net.minecraft.server.dedicated.DedicatedServer.bg()'`

![](https://i.imgur.com/7aQWDVl.png)

**Comment by jpenilla** [comment]
Known issues in mappings generation have been resolved. Please open new issues for any newly discovered edge cases.
