### ISSUE TITLE
Implement userdev plugin

### ISSUE THREAD

**Issue by DenWav** [PaperMC/paperweight#47]

**Comment by Scrayos** [comment]
Is there any feasible workaround for development against NMS code, until this plugin arrives?

**Comment by DarkArc** [comment]
> Is there any feasible workaround for development against NMS code, until this plugin arrives?

Do things the old way; target the reobf jar and work with mangled names (this is what I did the other day https://github.com/packet-loss-gaming/Hackbook/commit/084df087a526b0399776a433a5a68f300858805f). Alternatively, using Spigot's "special source" _should_ work if you want to go through the trouble and/or have a maven based build system.

**Comment by Scrayos** [comment]
> Alternatively, using Spigot's "special source" should work if you want to go through the trouble and/or have a maven based build system.

Seems like I'm out of luck. Just the other day, we migrated our whole codebase to Gradle.

> Do things the old way; target the reobf jar and work with mangled names (this is what I did the other day packet-loss-gaming/Hackbook@084df08).

I've already prepared a patch for this, but I hesitate to merge it, because the maintainability is just so much worse. 

Is there any rough estimate on when this userdev plugin could arrive? Is there any way to help/participate in the development of said plugin?
